repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: import-smoke
        name: Import smoke (ods2sql)
        entry: bash -c 'PYTHONPATH=src python -c "import ods2sql; print(\"import ok\")"'
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: adr-index-sync
        name: ADR index includes newest ADR file
        entry: python scripts/check_adr_index.py
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: no-debug-prints
        name: Disallow raw print without file= in src
        entry: bash scripts/check_prints.sh
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: run-selected-tests
        name: Fast sanity tests
        entry: bash scripts/fast_tests.sh
        language: system
        pass_filenames: false
        stages: [pre-push]
