name: Bug Report
description: File a bug report
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `./ods2sql.py --version`
      placeholder: 0.1.0
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of the bug.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Small ODS or Python snippet preferred.
  - type: dropdown
    id: dialect
    attributes:
      label: SQL Dialect
      options:
        - sqlite
        - postgres
        - mysql
  - type: textarea
    id: logs
    attributes:
      label: Relevant output
      description: Copy-paste any error logs or warnings.
      render: shell
