name: Feature Request
description: Propose an idea or improvement
labels: [enhancement]
body:
  - type: input
    id: context
    attributes:
      label: Context
      description: What problem are you trying to solve?
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What should change, and why?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: checkboxes
    id: scope
    attributes:
      label: Scope
      options:
        - label: Adds tests
        - label: Updates docs/README
        - label: Requires ADR update
